name: Render PlantUML diagrams

on:
  push:
    branches:
      - main

jobs:
  render-plantuml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PlantUML
        run: sudo apt-get install plantuml

      - name: Render PlantUML diagrams
        run: plantuml -tsvg plantuml/vehicle-truck-passengercar-cld.puml -o vehicle-truck-passengercar-cld.svg

      - name: Push generated image
        run: |
          mv plantuml/vehicle-truck-passengercar-cld.svg images/
          cd images
          ls -lah
          git add vehicle-truck-passengercar-cld.svg
          git commit -m "Update generated image"
          git push origin main
